spring.application.name=ReformApi

# CORE DATABASE (Neon PostgreSQL)
# ----------------------------------------
spring.datasource.url=${NEONDB_URI}
spring.datasource.username=neondb_owner
spring.datasource.password=${NEONDB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Auto-generate tables and JSONB columns
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# HikariCP pool tuning for Neon serverless
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000

# 1. OPENROUTER CONFIGURATION (For Chat / Generation)
#spring.ai.openai.chat.base-url=https://openrouter.ai/api
#spring.ai.openai.chat.api-key=${OPENROUTER_KEY}
#spring.ai.openai.chat.options.model=nex-agi/nex-n2.5-pro:free

spring.ai.openai.chat.base-url=https://api.openai.com
spring.ai.openai.chat.api-key=${EMBEDDING_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
#gpt-6-luna

# 2. OFFICIAL OPENAI CONFIGURATION (For Embeddings)
spring.ai.openai.embedding.base-url=https://api.openai.com
spring.ai.openai.embedding.api-key=${EMBEDDING_KEY}
spring.ai.openai.embedding.options.model=text-embedding-3-small

# Disable unused OpenAI services to prevent missing API key crashes
# Dummy key to bypass Spring AI's aggressive Audio/Image startup checks
spring.ai.openai.api-key=dummy-key-to-bypass-crash
spring.ai.openai.audio.speech.enabled=false
spring.ai.openai.audio.transcription.enabled=false
spring.ai.openai.image.enabled=false

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

server.servlet.context-path=/api/v1.0


clerk.issuer=https://full-mule-12.clerk.accounts.dev
clerk.jwks-url=https://full-mule-12.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

#file upload configuration
spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=250MB

razorpay.api.key=rzp_test_TJnAtswgk0kYRH
razorpay.api.secret=${RAZORPAY_API_SECRET}

minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:cloudshare_admin}
minio.secret-key=${MINIO_SECRET_KEY:cloudshare_password}
minio.bucket-name=${MINIO_BUCKET_NAME:cloudshare-files}


server.port=${PORT:8080}